name: Release new package
on: 
  push:
    branches:
      - master
    tags:
      - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install dependencies
        run: npm install

      - name: Package VSCode extension
        run: |
          npm install -g vsce
          vsce package

      - name: Auto-increment version and tag
        id: versioning
        run: |
          # Increment the version and create a new tag
          NEW_VERSION=$(npm version patch -m "Release version %s")
          echo "New version: $NEW_VERSION"
          # Output the new tag
          echo "new_tag=$NEW_VERSION" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git push origin HEAD
          git push origin ${{ env.new_tag }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.new_tag }}
          name: Release ${{ env.new_tag }}
          artifacts: ./*.vsix
          draft: false
          prerelease: false